BEGIN TRANSACTION;

DROP TABLE IF EXISTS red_wines
DROP TABLE IF EXISTS white_wines

CREATE TABLE red_wines (
    wine_id serial,
    varietal varchar(30) NOT NULL,
    country varchar(20) NOT NULL,
    state_or_region varchar(30) NOT NULL,
    sub_region varchar(30),
    color varchar(20),
    tannin varchar (20),
    alcohol varchar (20),
    body varchar (20),
    acidity varchar(20),
    sweetness varchar (20),
    has_oak boolean NOT NULL,
    fruit_condition varchar(20),
    fruit_type varchar(200),
    nonfruit_notes varchar(200),
    climate varchar (20),
    old_new_world char(2)
);

CREATE TABLE white_wines (
    wine_id serial,
    varietal varchar(30) NOT NULL,
    country varchar(20) NOT NULL,
    state_or_region varchar(30) NOT NULL,
    sub_region varchar(30),
    color varchar(20),
    alcohal varchar (20),
    body varchar (20),
    acidity varchar(20);
    sweetness varchar (20),
    has_oak boolean NOT NULL,
    fruit_condition varchar(20),
    fruit_type varchar(200),
    nonfruit_notes varchar(200),
    climate varchar (20),
    old_new_world char(2)
);

INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Cabernet Sauvignon', 'France', 'Bordeaux', 'Medoc', 'purple', 'moderate plus', 'moderate', 'medium', 'moderate plus', 'dry', TRUE, 'tart, ripe', 'black', 'green pepper, cocoa, vanilla, leather, smoke', 'cool', 'OW');
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Cabernet Sauvignon', 'Australia', 'South Australia', 'Coonawarra', 'purple', 'moderate plus', 'high', 'full', 'moderate', 'dry', TRUE, 'overripe, dried', 'black', 'eucalyptus, vanilla', 'warm', 'OW');
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Cabernet Sauvignon', 'Chile', 'Central Valley', 'Aconcagua', 'purple', 'moderate plus', 'high', 'full', 'moderate plus', 'dry', TRUE, 'ripe', 'black', 'dried herbs, smoke, vanilla, toast', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Cabernet Sauvignon', 'USA', 'California', 'Napa Valley', 'purple', 'high', 'high', 'full', 'low', 'dry', TRUE, 'ripe, overripe', 'black', 'mint, cocoa, dried herbs, mineral, floral, vanilla', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Cabernet Franc', 'France', 'Loire Valley', 'Chinon', 'ruby', 'moderate plus', 'moderate', 'medium', 'moderate', 'dry', FALSE, 'tart to ripe', 'red', 'green pepper, vegetal, herbacious, game, rock, mint', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Cabernet Franc', 'France', 'Loire Valley', 'Bourgueil', 'ruby', 'moderate plus', 'moderate', 'medium', 'moderate', 'dry', FALSE, 'tart to ripe', 'red', 'green pepper, vegetal, herbacious, game, rock, mint', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Carmenere', 'Chile', 'Central Valley', 'Curico', 'ruby', 'moderate', 'moderate plus', 'moderate', 'moderate plus', 'dry', TRUE, 'ripe', 'red, blue', 'bell pepper, peppercorn, vanilla, mineral', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Carmenere', 'Chile', 'Central Valley', 'Maipo', 'ruby', 'moderate', 'moderate plus', 'moderate', 'moderate plus', 'dry', TRUE, 'ripe', 'red, blue', 'bell pepper, peppercorn, vanilla, mineral', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Carmenere', 'Chile', 'Central Valley', 'Maule', 'ruby', 'moderate', 'moderate plus', 'moderate', 'moderate plus', 'dry', TRUE, 'ripe', 'red, blue', 'bell pepper, peppercorn, vanilla, mineral', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Corvina-based blend', 'Italy', 'Veneto', 'Amarone', 'garnet', 'moderate minus', 'high', 'moderate' 'full', 'moderate plus', 'off-dry', TRUE, 'overripe, dried', 'red, black', 'cocoa, coffee, peppercorn, stone', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Corvina-based blend', 'Italy', 'Veneto', 'Valpolicella', 'ruby', 'moderate minus', 'moderate', 'moderate', 'high', 'dry', FALSE, 'tart, ripe', 'red', 'cocoa, peppercorn', 'cool', 'OW' ); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Gamay Noir', 'France', 'Beaujolais', 'Cru Beaujolais', 'purple', 'low', 'moderate minus', 'moderate minus', 'light', 'moderate plus', 'dry', FALSE, 'ripe', 'red', 'floral, forest floor', 'cool', 'OW' ); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Grenache/Grenache-based blend', 'France', 'Southern Rhone Valley', 'Châteauneuf-du-Pape', 'ruby', 'moderate', 'high', 'full', 'moderate', 'dry', FALSE, 'ripe, overripe', 'red', 'dried herbs, tomato leaf, leather, peppercorn, floral', 'warm', 'OW'  ); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Grenache/Grenache-based blend', 'France', 'Southern Rhone Valley', 'Gigondas', 'ruby', 'moderate', 'moderate', 'medium', 'moderate', 'dry', FALSE, 'ripe', 'red', 'dried herbs, tomato leaf, leather, peppercorn, floral', 'warm', 'OW'  ); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Grenache/Grenache-based blend', 'France', 'Southern Rhone Valley', 'Vacqueryas', 'ruby', 'moderate', 'moderate', 'medium', 'moderate', 'dry', FALSE, 'ripe', 'red', 'dried herbs, tomato leaf, leather, peppercorn, floral', 'warm', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Grenache', 'Australia', 'South Australia', null, 'ruby', 'moderate', 'moderate plus', 'full', 'moderate', 'dry', FALSE, 'overripe', 'red', 'dried herbs, tomato leaf,  peppercorn, floral', 'warm', 'NW'  ); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Malbec', 'Argentina', 'Mendoza', null, 'purple', 'moderate', 'moderate plus', 'full', 'moderate minus', 'dry', FALSE, 'ripe, overripe', 'red, black', 'vanilla, cocoa, tobacco', 'moderate', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Merlot', 'France', 'Bordeaux', 'St. Emillion', 'ruby', 'moderate', 'moderate plus', 'medium', 'low', 'dry', TRUE, 'ripe', 'red, black', 'cocoa, vanilla, mushrooms', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Merlot', 'USA', 'California', 'Napa Valley', 'ruby', 'moderate plus', 'moderate plus', 'moderate', 'ripe', 'red, black', 'mint, eucalyptus, mocha', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Nebbiolo', 'Italy', 'Piedmont', 'Barolo', 'garnet', 'high', 'moderate plus', 'full', 'high', 'dry', FALSE, 'dried', 'red', 'tar, floral, mushroom, leather, dried herbs', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Nebbiolo', 'Italy', 'Piedmont', 'Barbaresco', 'garnet', 'moderate plus', 'moderate plus', 'moderate plus', 'high', 'dry', FALSE, 'ripe', 'red', 'tar, floral', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Pinot Noir', 'France', 'Burgundy', 'Cote dOr', 'ruby', 'low', 'moderate', 'moderate', 'high', 'dry', TRUE, 'ripe', 'red', 'forest floor, mushroom, game, mineral', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Pinot Noir', 'USA', 'California', 'Russian River Valley', 'ruby', 'low', 'moderate', 'moderate', 'moderate plus', 'dry', TRUE, 'overripe', 'red', 'mushroom, forest floor', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Pinot Noir', 'USA', 'Oregon', 'Willamette Valley', 'ruby', 'low', 'moderate', 'moderate', 'high', 'dry', TRUE, 'ripe', 'red', 'floral, mint', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Sangiovese', 'Italy', 'Tuscany', 'Brunello di Montalcino', 'ruby', 'high', 'high', 'medium', 'high', 'dry', TRUE, 'ripe, dried', 'dried herbs, leather, smoke', 'moderate', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Sangiovese', 'Italy', 'Tuscany', 'Chianti', 'ruby', 'moderate plus', 'moderate plus', 'medium', 'high', 'dry', FALSE, 'tart, ripe', 'red', 'dried herb, leather, smoke', 'moderate', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Syrah', 'France', 'Northern Rhone Valley', 'Hermitage', 'purple', 'high', 'high', 'full', 'moderate', 'dry', FALSE, 'ripe', 'red, black, blue', 'peppercorn, cured meat, cocoa, leather, dried herbs, floral', 'cool', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Syrah','Australia', 'South Australia', 'Barossa Valley', 'purple', 'moderate', 'high', 'full', 'low', 'dry', TRUE, 'jammy', 'black', 'eucalyptus, peppercorn, mocha', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Zinfandel', 'USA', 'California', 'Paso Robles', 'purple', 'moderate', 'high', 'full', 'low', 'dry', TRUE, 'jammy', 'red', 'coconut, dried herbs', 'warm', 'NW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Tempranillo', 'Spain', 'Ribera del Duero', null, 'purple', 'moderate plus', 'moderate plus', 'full', 'moderate', 'dry', TRUE, 'ripe, stewed', 'black', 'leather, coconut, vanilla, game, smoke', 'moderate', 'OW'); 
INSERT INTO red_wines (varietal, country, state_or_region, sub_region, color, tannin, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Tempranillo', 'Spain', 'Rioja', null, 'garnet', 'moderate', 'moderate', 'medium', 'low', 'dry', TRUE, 'stewed', 'red', 'leather, vanilla, coconut, game', 'moderate', 'OW'); 

INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Riesling', 'Germany', 'Rheingau',  'none', 'yellow', 'moderate', 'medium', 'high', 'dry', FALSE, 'ripe', 'citrus, stone fruit', 'mineral, stone', 'cool', 'OW' );
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Riesling', 'France', 'Alsace', 'none', 'yellow', 'moderate', 'medium', 'high', 'dry', FALSE,'ripe',  'orchard, stone fruit', 'smoke, honey, herbal', 'moderate', 'OW' );
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Riesling', 'Austria', 'Kamptal', 'none', 'straw', 'moderate', 'medium', 'high', 'dry', FALSE, 'tart, ripe', 'citrus, stone fruit', 'mineral', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Riesling', 'Australia', 'Clare Valley',  'none', 'straw', 'moderate', 'light', 'high', 'dry', FALSE, 'tart', 'citrus', 'mineral, wax, yeast', 'cool', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Sauvignon Blanc', 'France', 'Loire', 'Sancerre',  'yellow', 'moderate', 'light', 'high', 'dry', FALSE,  'tart', 'citrus', 'vegetal, smoke, mineral', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Sauvignon Blanc', 'France', 'Bordeaux', 'Pessac-Leognan', 'yellow', 'moderate', 'medium', 'medium', 'dry', TRUE, 'tart', 'citrus, stone fruit', 'mineral, wax, nutty', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Sauvignon Blanc', 'USA', 'California', 'Napa', 'yellow', 'moderate', 'medium', 'moderate', 'dry', TRUE,  'ripe', 'citrus, tropical', 'herbal, smoke', 'warm', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Sauvignon Blanc', 'New Zealand', 'South Island', 'Marlborough',  'yellow', 'moderate plus', 'medium', 'high', 'dry', FALSE, 'ripe, overripe', 'citrus, tropical', 'vegetal, creamy', 'warm', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Torrentes', 'Argentina', 'Catamarca', 'none', 'straw', 'moderate', 'medium', 'moderate plus', 'off-dry', FALSE, 'ripe', 'citrus, stone fruit', 'floral, herbal', 'cool', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Viognier', 'France', 'Rhône Valley',  'Condrieu',  'gold', 'high', 'full', 'low', 'dry', FALSE, 'ripe, overripe', 'stone fruit', 'floral, honey, spice', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Viognier', 'USA', 'California', 'Central Coast', 'gold', 'high', 'full', 'low', 'dry', FALSE, 'ripe, overripe', 'stone fruit', 'floral, honey, spice', 'warm', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Riesling', 'Germany', 'Mosel',  'none', 'straw', 'low', 'light', 'high', 'off-dry', FALSE, 'tart, ripe', 'citrus, stone fruit', 'mineral, stone, floral', 'cool', 'OW' );
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Pinot Gris', 'USA', 'Oregon', 'none', 'straw', 'moderate', 'medium', 'moderate plus', 'dry', FALSE, 'tart', 'orchard, stone fruit', 'nutty, floral, mineral', 'cool', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Pinot Gris', 'Italy', 'Friuli', 'none', 'straw', 'moderate', 'medium', 'moderate plus', 'dry', FALSE, 'tart', 'orchard, stone fruit', 'nutty, floral, mineral', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Pinot Gris', 'France', 'Alsace', 'none', 'yellow', 'moderate', 'medium', 'moderate plus', 'dry, off dry', FALSE, 'tart', 'orchard, stone fruit', 'smoke, spice, floral, honey', 'moderate', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Gruner Veltliner', 'Austria', 'Kamptal', 'none', 'straw', 'moderate minus', 'light', 'high', 'dry', FALSE, 'tart, ripe', 'citrus',  'vegetal, herbal, spice, mineral', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Gewurztraminer', 'France',  'Alsace', 'none', 'gold', 'high', 'full', 'low', 'off-dry', FALSE, 'ripe, overripe', 'citrus, stone fruit', 'floral, ginger, smoke, spice', 'moderate', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Chenin Blanc', 'France', 'Loire Valley', 'Savennieres', 'gold', 'moderate plus', 'full', 'moderate plus', 'dry', FALSE, 'ripe, overripe', 'orchard, stone fruit', 'waxy, floral, nutty', 'cool', 'OW'  );
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Chenin Blanc', 'France', 'Loire Valley', 'Vouvray', 'yellow', 'moderate', 'medium', 'moderate plus', 'off-dry', FALSE, 'ripe', 'orchard, stone fruit', 'floral, honey', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Chardonnay', 'Australia', 'New South Wales', 'Hunter Valley', 'gold', 'moderate plus', 'medium', 'moderate', 'dry', FALSE, 'ripe, overripe', 'stone fruit, tropical', 'floral', 'warm', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Chardonnay', 'USA', 'Napa', 'Russian River Valley', 'gold', 'high', 'full', 'low', 'dry', TRUE, 'ripe, overripe', 'orchard, tropical', 'butter, vanilla, baked bread', 'warm', 'NW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Chardonnay', 'France', 'Burgundy', 'Cote dOr', 'yellow', 'moderate plus', 'full', 'moderate plus', 'dry', TRUE, 'ripe', 'citrus, orchard', 'vanilla, spice, buttery, mineral', 'cool', 'OW');
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Chardonnay', 'France', 'Burgundy', 'Chablis', 'straw', 'moderate minus', 'light', 'high', 'dry', FALSE, 'tart, ripe', 'citrus, orchard', 'stone, creamy', 'cool', 'OW' );
INSERT INTO white_wines (varietal, country, state_or_region, sub_region, color, alcohol, body, acidity, sweetness, has_oak, fruit_condition, fruit_type, nonfruit_notes, climate, old_new_world) VALUES ('Albarino',  'Spain', 'Galicia', 'Rias Baixas', 'yellow', 'moderate', 'medium', 'high', 'dry', FALSE, 'tart, ripe', 'citrus, orchard', 'floral, nutty, stone', 'moderate', 'OW');

COMMIT;

